"""creat db

Revision ID: a0451d7aaa0a
Revises: 
Create Date: 2024-11-17 09:59:48.906247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0451d7aaa0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('account')
    op.drop_table('booking_status')
    op.drop_table('booking')
    op.drop_table('booking_method')
    op.drop_table('payment_method')
    op.drop_table('invoice_detail')
    op.drop_table('room_status')
    op.drop_table('address')
    op.drop_table('passport')
    op.drop_table('service_type')
    op.drop_table('employee')
    with op.batch_alter_table('renting_detail', schema=None) as batch_op:
        batch_op.drop_index('room_renting_unique')

    op.drop_table('renting_detail')
    op.drop_table('service')
    op.drop_table('renting')
    op.drop_table('room_type')
    with op.batch_alter_table('booking_detail', schema=None) as batch_op:
        batch_op.drop_index('booking_roomType_unique')

    op.drop_table('booking_detail')
    op.drop_table('invoice')
    op.drop_table('customer')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('countryName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('fullName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phoneNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('citizenIdentificationCard', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dateOfBirth', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invoice',
    sa.Column('totalMoney', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('deposit', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('surcharge', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('discount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('paymentMethod_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='invoice_ibfk_2'),
    sa.ForeignKeyConstraint(['paymentMethod_id'], ['payment_method.id'], name='invoice_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('booking_detail',
    sa.Column('numberRooms', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('booking_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('roomType_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='booking_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['roomType_id'], ['room_type.id'], name='booking_detail_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('booking_detail', schema=None) as batch_op:
        batch_op.create_index('booking_roomType_unique', ['booking_id', 'roomType_id'], unique=True)

    op.create_table('room_type',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('maxNumberOfCustomer', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('renting',
    sa.Column('checkInDate', mysql.DATETIME(), nullable=True),
    sa.Column('checkOutDate', mysql.DATETIME(), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('invoice_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='renting_ibfk_2'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='renting_ibfk_1'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='renting_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('service',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('price', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('unit', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('serviceType_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['serviceType_id'], ['service_type.id'], name='service_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('renting_detail',
    sa.Column('room_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('renting_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='renting_detail_ibfk_3'),
    sa.ForeignKeyConstraint(['renting_id'], ['renting.id'], name='renting_detail_ibfk_2'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='renting_detail_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('renting_detail', schema=None) as batch_op:
        batch_op.create_index('room_renting_unique', ['room_id', 'renting_id'], unique=True)

    op.create_table('employee',
    sa.Column('workingDate', mysql.DATETIME(), nullable=True),
    sa.Column('salary', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('fullName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phoneNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('citizenIdentificationCard', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dateOfBirth', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('service_type',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('passport',
    sa.Column('firstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ppNumber', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('country_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='passport_ibfk_2'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='passport_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('address',
    sa.Column('address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('country_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='address_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('room_status',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invoice_detail',
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('totalMoney', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('invoice_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('service_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='invoice_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='invoice_detail_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment_method',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('booking_method',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('booking',
    sa.Column('checkInDate', mysql.DATETIME(), nullable=True),
    sa.Column('checkOutDate', mysql.DATETIME(), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('numberRooms', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numberStayGuests', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deposit', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('customer_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('bookingMethod_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('bookingStatus_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookingMethod_id'], ['booking_method.id'], name='booking_ibfk_3'),
    sa.ForeignKeyConstraint(['bookingStatus_id'], ['booking_status.id'], name='booking_ibfk_4'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='booking_ibfk_1'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='booking_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('booking_status',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account',
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('userRole', mysql.ENUM('ADMIN', 'EMPLOYEE', 'CUSTOMER'), nullable=True),
    sa.Column('customer_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='account_ibfk_1'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='account_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('room',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('note', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('floor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('thumbnail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('roomStatus_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('roomType_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['roomStatus_id'], ['room_status.id'], name='room_ibfk_1'),
    sa.ForeignKeyConstraint(['roomType_id'], ['room_type.id'], name='room_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
